### ISSUE TITLE
Setting to hide closed temporary containers

### ISSUE THREAD

**Issue by Perflyst** [stoically/firefox-add-on-switch-container-plus#1]
It would be nice if there is a function to hide closed temporary containers.

Since with the [Temporary Containers Addon](https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/) the containers are removed completely after 15 minutes by default, it is annoying to see containers that are no longer needed in the Switch Container list after some time.

**Comment by stoically** [comment]
Cool idea, I'll look into implementing it.

**Comment by DorianScholz** [comment]
Great idea!
Since I only switch tabs into persistent containers and never into temp ones, would it be possible for you to add an option to hide all temporary containers?
And I guess also an option is needed to specify which prefix the temp containers use, since that can be customized in the temp container addon...

Thanks for your enhancements of this nice addon, with your version I can finally see the toolbar icon ;-)

**Comment by DorianScholz** [comment]
I implemented this in https://github.com/stoically/switch-container-plus/pull/4
It now has a settings page where you can enter a regex matching the containers you want to hide, e.g. "^tmp" to hide all starting with "tmp".
